export const tweetsData = [   
  {
      handle: `@erythchi ☣️`,
      profilePic: `image/clau.jpg`,
      likes: 27,
      retweets: 10,
      tweetText: `Compraré muchos Bitcoin💰💰💰 para comprar todos los cosplay que me gustan`,
      replies: [],
      isLiked: false,
      isRetweeted: false,
      isReplyVisible: false,
      canDelete: false,
      uuid: '4b161eee-c0f5-4545-9c4b-8562944223ee',
  },    
  {
      handle: `@drkedrkedjon 💩`,
      profilePic: `image/sasa.jpg`,
      likes: 6500,
      retweets: 234,
      tweetText: `I need volunteers for a one-way mission to Mars 🪐. No experience necessary🚀`,
      replies: [
                {
              handle: `@xilerth 😎`,
              profilePic: `image/luis.jpg`,
              tweetText: `Yes! Sign me up! 😎🛩`,
          },
                {
              handle: `@drkedrkedjon 💩`,
              profilePic: `image/sasa.jpg`,
              tweetText: `I went last year😴`,
          },
      ],
      isLiked: false,
      isRetweeted: false,
      isReplyVisible: false,
      canDelete: false,
      uuid: '3c23454ee-c0f5-9g9g-9c4b-77835tgs2',
  },
      {
      handle: `@xilerth 😎`,
      profilePic: `image/luis.jpg`,
      likes: 10,
      retweets: 3,
      tweetText: `Are you a coder if you only know AngularJS?`,
      replies: [
          {
              handle: `@erythchi ☣️`,
              profilePic: `image/clau.jpg`,
              tweetText: `No. Obviosuly not. Go get a job in McDonald's.`,
          },
          {
              handle: `@drkedrkedjon 💩`,
              profilePic: `image/sasa.jpg`,
              tweetText: `You are wonderful just as you are! ❤️`,
          },
      ],
      isLiked: false,
      isRetweeted: false,
      isReplyVisible: false,
      canDelete: false,
      uuid: '8hy671sff-c0f5-4545-9c4b-1237gyys45',
  },     
]